### ISSUE TITLE
Is possible to hide items?

### ISSUE THREAD

**Issue by Ainsdev** [weta-vn/freemar_image_picker#4]
In the same app I only want to use the camera and not the album in some cases or for example only use the back camera.
Is possible to do that??
I also have to mention very good work!! it is all very complete .

**Comment by weta-vn** [comment]
@Ainsdev 
Thank you very much.
We added these functions into new released version. Please confirm.
advance_image_picker: ^0.0.3

**Comment by Ainsdev** [comment]
Hello, you mean  PickerMode? if yes, how do you used? Where I put it??

**Comment by Ainsdev** [comment]
Amazing package, I think I will use it in my final app.
I do not know if it is my device, but the only bad thing I see is that it takes about 3s to take a photo and is Lag sometimes.
But for the rest, excellent work!
Greetings from Chile
